## Exercício 1: Vestibular
Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1 - (operações com escalar) Calcule o percentual de acerto dos alunos por assunto;

2 - (operações entre *DataFrames) Calcule o total de acertos de cada aluno;

3 - Calcule o porcentual geral de cada aluno;

4 - Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [56]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [57]:
df_mat

    Qt_acertos
0            6
1           19
2           14
3           10
4            7
..         ...
95           6
96           8
97          23
98           0
99          11

[100 rows x 1 columns]

In [58]:
# 1 - (operações com escalar) Calcule o percentual de acerto dos alunos por assunto;

perc_mat = df_mat / 24
perc_port = df_por / 18
perc_geo = df_geo / 8
perc_ing = df_ing / 8
perc_hist = df_his / 8
perc_fis = df_fis / 12
perc_qui = df_qui / 12

In [59]:
# 2 - (operações entre *DataFrames) Calcule o total de acertos de cada aluno;
acertos = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui
acertos

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [60]:
# 3 - Calcule o porcentual geral de cada aluno;
perc_geral = acertos / 90
perc_geral

    Qt_acertos
0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
..         ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667

[100 rows x 1 columns]

In [61]:
# Modelo arredondado da porcentagem
perc_arredondado = ((acertos/90)*100).round(2)
perc_arredondado

    Qt_acertos
0        38.89
1        53.33
2        55.56
3        35.56
4        33.33
..         ...
95       37.78
96       30.00
97       44.44
98       44.44
99       46.67

[100 rows x 1 columns]

In [62]:
# 4 - Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

aprovados = acertos[acertos['Qt_acertos'] > 45]
aprovados.count()

Qt_acertos    31
dtype: int64

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [63]:
# 1 - Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo DataFrame com os alunos desqualificados por este critério. 
df_reprovados = acertos[(df_mat['Qt_acertos'] == 0)|
                       (df_fis['Qt_acertos'] == 0) |
                       (df_qui['Qt_acertos'] == 0)]

df_reprovados

    Qt_acertos
3           32
6           29
10          31
12          42
14          31
20          53
25          27
26          40
27          50
33          39
35          48
49          19
56          39
65          24
66          31
72          50
73          37
74          39
84          26
89          63
92          40
94          25
98          40

In [64]:
# modelo mais detalhado do exercicio acima
#Matematica

df_mat['matematica'] = df_mat['Qt_acertos']
df_mat.drop(['Qt_acertos'], axis='columns', inplace=True)

#Portugues
df_por['portugues'] = df_por['Qt_acertos']
df_por.drop(['Qt_acertos'], axis='columns', inplace=True)

#Geografia
df_geo['geografia'] = df_geo['Qt_acertos']
df_geo.drop(['Qt_acertos'], axis='columns', inplace=True)

#Ingles
df_ing['ingles'] = df_ing['Qt_acertos']
df_ing.drop(['Qt_acertos'], axis='columns', inplace=True)

#Historia
df_his['historia'] = df_his['Qt_acertos']
df_his.drop(['Qt_acertos'], axis='columns', inplace=True)

#Fisica
df_fis['fisica'] = df_fis['Qt_acertos']
df_fis.drop(['Qt_acertos'], axis='columns', inplace=True)

#quimica
df_qui['quimica'] = df_qui['Qt_acertos']
df_qui.drop(['Qt_acertos'], axis='columns', inplace=True)

In [65]:
# construindo novo dataframe mais detalhado
df_concat = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1, join='outer')
df_concat

    matematica  portugues  geografia  ingles  historia  fisica  quimica
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
3           10          7          3       4         0       0        8
4            7          2          2       7         0       9        3
..         ...        ...        ...     ...       ...     ...      ...
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
98           0         10          3       1         5      10       11
99          11         15          0       1         6       7        2

[100 rows x 7 columns]

In [66]:
# separando quem zerou em matematica, fisica e quimica

desc_mat = df_concat.loc[(df_concat['matematica'] == 0)]
desc_fis = df_concat.loc[(df_concat['fisica'] == 0)]
desc_qui = df_concat.loc[(df_concat['quimica'] == 0)]

In [67]:
# criando df dos desclassificados

df_desclassificados = pd.concat([desc_mat, desc_fis, desc_qui], axis=0, join='outer')
df_desclassificados.drop_duplicates(inplace=True)

df_desclassificados

    matematica  portugues  geografia  ingles  historia  fisica  quimica
25           0          4          7       4         0       4        8
94           0          5          2       6         1       3        8
98           0         10          3       1         5      10       11
3           10          7          3       4         0       0        8
6            6          0          7       7         5       0        4
12          20          8          3       7         1       0        3
26          11         14          6       2         7       0        0
35          11         14          6       3         3       0       11
49           8          1          1       0         1       0        8
56           7          6          7       5         6       0        8
65           1          8          2       4         3       0        6
66           5          4          3       6         3       0       10
72          11         16          3       4         7       0        9
73           1         16          2       4         3       0       11
84          15          1          0       5         1       0        4
10          10          8          3       2         1       7        0
14           7         11          1       7         1       4        0
20          23         11          6       5         6       2        0
27          21         13          1       5         7       3        0
33          14          8          0       5         6       6        0
74           9         11          0       7         5       7        0
89          23         11          7       7         6       9        0
92          14         10          1       6         1       8        0

In [68]:
# 2 - Quantos são esses alunos?
df_desclassificados.shape[0]

23

In [69]:
# 3 - Qual a média desses alunos em história e geografia?

df_hist_media = df_desclassificados['historia'].mean()

df_hist_media

3.4347826086956523

In [70]:
df_desclassificados['geografia'].mean()

3.217391304347826

In [71]:
# 4 - Monte um DataFrame com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.
# Unindo Df Aprovados e Df eliminados
df_aprovados = df_concat[(df_concat['matematica'] != 0) &  (df_concat['fisica'] != 0) & (df_concat['quimica'] != 0)]
df_aprovados

    matematica  portugues  geografia  ingles  historia  fisica  quimica
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
4            7          2          2       7         0       9        3
5           20          2          5       3         2       9        9
..         ...        ...        ...     ...       ...     ...      ...
93          12         16          5       5         6       6        6
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
99          11         15          0       1         6       7        2

[77 rows x 7 columns]

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [16]:
vacAcre_df = pd.read_csv('vacinacao_covid_ACRE.csv', sep=';')

In [17]:
vacAcre_df.head(5)

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN

In [18]:
# 1 - Quantas vacinas estão registradas nessa base?  
vacAcre_df.shape[0]

169071

In [19]:
# 2 - Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```) 
df_pac_uniq = vacAcre_df['paciente_id'].nunique()
df_pac_uniq

120517

In [20]:
# 3 - Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.
primeira_dose = vacAcre_df['vacina_descricao_dose'].unique()[0]
vacAcre_df['paciente_id'].loc[vacAcre_df['vacina_descricao_dose'] == primeira_dose].nunique()

119713

In [21]:
# 4 - Quantos pacientes com menos de 18 anos foram vacinados? 
pacientes_18anos = vacAcre_df[vacAcre_df['paciente_idade'] < 18]
pacientes_18anos['paciente_id'].count()

55

In [22]:
# 5 - Quantos estabelecimentos aplicaram vacina no Acre?
df_ac = vacAcre_df.loc[vacAcre_df['estabelecimento_uf'] == 'AC'].count()
df_ac['estabelecimento_uf']

169071

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [23]:
#1 - crie uma cópia do DataFrame original, contendo somente os registros de vacinas realizadas a menores de 18 anos.
menor_df = vacAcre_df[vacAcre_df['paciente_idade'] < 18].copy()
menor_df.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
1567,fdca313f-b348-422d-94d4-f2c66a87868c-i0b0,f5e6b8c44f7c4d13a87c582def5e8d460435b02f26af8c...,17,2003-07-18,F,4,AMARELA,120025.0,10.0,EPITACIOLANDIA,...,213VCD003W,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-05-12,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-13T16:16:42.000Z,NaN
6250,b7431955-1faa-4c1e-9246-7c1e7b8bb3cb-i0b0,e1a45c07e3c393d5f0eccf4204a7ceab338f4f06696ecb...,16,2004-05-18,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,200278,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-29,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-06T14:02:07.000Z,NaN
9569,fdb8d3b6-14d9-4bcc-9cfe-acd46b4a317a-i0b0,7cf3b238383a70eeb26841c01817737c9706d5b231e8c2...,17,2004-01-23,F,99,SEM INFORMACAO,120020.0,10.0,CRUZEIRO DO SUL,...,213VCD042Z,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-05-15,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-18T03:17:02.000Z,NaN
11338,647e2301-3ba4-463a-8d1e-2b6f38a4d99e-i0b0,53eb7fed5faa26ad17ce21ee378f28e25399ab7e90bc05...,17,2003-05-04,F,4,AMARELA,120030.0,10.0,FEIJO,...,4120Z004,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-02-09,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-02-09T22:08:13.000Z,NaN
15144,7f469e03-bece-49d0-bebc-33ad98e27f54-i0b0,dbaa6420d8a815158387668d0a59a19cf2bb63958e35d1...,16,2004-08-22,F,5,INDIGENA,120035.0,10.0,MARECHAL THAUMATURGO,...,202010028,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-28,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-09T19:26:03.000Z,NaN

In [24]:
# 2 - crie uma lista das colunas desse DataFrame com o atributo de DataFrame .columns()
variaveis = menor_df.columns
print(variaveis)

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [25]:
# 3 - Nesse DataFrame faça uma contagem do campo vacina_categoria_nome.
menor_df['vacina_categoria_nome'].value_counts()

Povos Indígenas                     33
Povos e Comunidades Tradicionais     9
Trabalhadores de Saúde               9
Comorbidades                         2
Faixa Etária                         1
Name: vacina_categoria_nome, dtype: int64

In [26]:
# 4 - a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.
lista_variaveis = menor_df.loc[:,'estabelecimento_valor':'estabelecimento_uf'].columns.unique()
lista_variaveis

Index(['estabelecimento_valor', 'estabelecimento_razaosocial',
       'estalecimento_nofantasia', 'estabelecimento_municipio_codigo',
       'estabelecimento_municipio_nome', 'estabelecimento_uf'],
      dtype='object')

In [27]:
# 5 - usando o método .loc, selecione somente essas variáveis
lista_var = ['estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf']
df_lista_menor = menor_df.loc[:,lista_var]
df_lista_menor

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
17153,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
18361,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
18608,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
20204,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
20759,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
21119,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
27860,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
29127,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
31200,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
35654,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
38412,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
51872,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
57405,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
61131,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
62742,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
66922,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
68290,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
69882,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
70881,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
75368,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
78289,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
79146,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
81424,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
84331,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
88619,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
89601,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
94858,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
95916,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
101402,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
104776,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
111242,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
116510,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
119906,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
122656,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
123769,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
124696,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
135392,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
136851,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
139074,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
140895,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC
142027,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
149043,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
149795,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
152218,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
153347,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
155238,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
161227,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
163168,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
164046,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
164449,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC

In [28]:
# 6 - Aplique o método .drop_duplicates e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento
df_lista_menor = df_lista_menor.drop_duplicates()
df_lista_menor

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
17153,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
18361,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
18608,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
20204,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
21119,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
29127,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
57405,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
61131,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
68290,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
69882,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
70881,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
101402,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
140895,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC